# Sensores autorizados - Mineria
MILL_VIB_001,vibration,Molino_Principal_Rodamiento_A
MILL_VIB_002,vibration,Molino_Principal_Rodamiento_B
MILL_TEMP_001,temperature,Molino_Principal_Motor
GAS_CO_001,gas,Galeria_Norte_Nivel_3
GAS_H2S_001,gas,Zona_Procesamiento
TANK_LVL_001,level,Tanque_Agua_Proceso
GPS_VEH_001,gps,Vehiculo_Perforacion_01
