#!/bin/bin/sh
export PATH=/bin:/sbin

# Montar sistemas de archivos del kernel
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true

clear
echo "=================================================================="
echo "          CHRONOOS KERNEL v7.5 - SOVEREIGN RUNTIME ACTIVE         "
echo "          Arch: x86_64 | Init System: BusyBox Native PID 1        "
echo "=================================================================="
echo "Escribe 'help' para ver los comandos del sistema o 'poweroff' para apagar."
echo ""

# Lanzar shell interactivo con control de errores del sistema
exec /bin/sh
